# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0004_extend_fields_length'),
        ('core_actuator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HERMSProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='HERMSProcessConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Name of this configuration', max_length=150)),
                ('m13', models.ForeignKey(help_text='Tap Cold Water input (Manual)', on_delete=django.db.models.deletion.CASCADE, to='core_actuator.ManualValve')),
                ('m2', models.ForeignKey(help_text='Cold Water in HLT Valve (Motorized)', on_delete=django.db.models.deletion.CASCADE, to='core_actuator.MotorizedValve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hermsprocess',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='herms_process.HERMSProcessConfiguration'),
        ),
    ]
